### PR TITLE
Fix missing CSP exception in NC16

### PR DESCRIPTION
**Pull request by MinIsMin**
The CSP exception URL requires host and path.
`host` is either given by settings or by `gethostname()` and ~~`path` only from settings~~ a `/`

### CODE REVIEW

**Comment by MinIsMin** [comment]
Now every case should work, tested with multiple environments.

Only the host and `/` is required, not the full path so we can add a `/` just to be sure, it doesn't matter if there's already one.

**Comment by sualko** [comment]
> The CSP exception URL requires host and path

That's wrong. The path is not required, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Sources

Also adding the web server host is useless, because therefore you should use the reserved `'self'`. Maybe I have some applications activated which add self to csp and therefore I can't reproduce your issue. Will try it asap and report back.

Nonetheless thanks for your time and effort.

**Comment by sualko** [comment]
Nextcloud creates different csp for Chrome and Firefox. I created a pr #71, which adds `self` also on FF. Would be awesome if you could test it @criegerde @MinIsMin

**Comment by sualko** [comment]
fixed in 3665c399baf9dcf69ad4c492f887f4043b857f29

**Pull request closed without merging**
